services:
  app:
    container_name: laravel_app
    build:
      context: ./php
    volumes:
      - ./php/src/example-app:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    working_dir: /var/www/html
    command: bash -c "composer install && php artisan migrate --force && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "9906:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_pma
    environment:
      PMA_HOST: db
      PMA_USER: my_user
      PMA_PASSWORD: my_password
    ports:
      - "8080:80"

volumes:
  dbdata:

