services:
  jenkins:
    build:
      context: .
    container_name: jenkins-server
    ports:
      - "8081:8080"   # interface Jenkins
      - "50000:50000" # agentes
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # permite rodar docker no host
      - ../:/home/jenkins/app   # monta a pasta pai (contendo app-docker-compose.yml)
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
